# Generated by Django 5.2.6 on 2025-09-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Interaction date')),
                ('kind', models.CharField(choices=[('I', 'Interview'), ('A', 'Assessment'), ('O', 'Offer'), ('R', 'Rejection'), ('X', 'Other')], default='I', max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.application')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
