# Generated by Django 5.2.6 on 2025-09-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main_app.tag'),
        ),
    ]
